name: Lint and Commit
on: 
  push:
    branches-ignore:    
      - 'release/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - uses: chartboost/ruff-action@v1
        with:
          fix_args: --fix .
          config: .ruff.toml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto fix by ruff"
